### ISSUE TITLE
Error in terms.formula(formula, data = data) :  'data' argument is of the wrong type

### ISSUE THREAD

**Issue by AdamSorrel** [sjPlot/sjmisc#18] opened 2016-02-09 14:58 UTC
Hi Daniel,

I'm having some strange issues with plotting model assumptions of linear model using:
`sjp.lm(lm.test, type = "ma")` 

on a following linear model 
`lm.test = lm(Chao1 ~ Water_content + N.NH4 + N.NO3 + OM + pH + Cl + K, df)`. 

It returns an error: 
_Error in terms.formula(formula, data = data) :  'data' argument is of the wrong type_

It behaves quite strangely, because when I take out the *water_content* variable, it suddenly works. I  tried renaming it, removing rows with NA values, but it wouldn't help.

I'm attaching the test data.

[test_data.csv.zip](https://github.com/sjPlot/sjmisc/files/123203/test_data.csv.zip)

Thanks a lot!

**Comment by AdamSorrel** [comment] 2016-02-09 15:23
I am really sorry for spamming. I was playing around and discovered that simply renaming the data frame with `df2 = df` resolves it. I guess you should still know about it.

**Comment by sjPlot** [comment] 2016-02-09 16:19
Ok, `df` is a reserved keyword (function) in R, so this seems to be the cause for the error. Anyway, I will check your sample file.

**Comment by sjPlot** [comment] 2016-02-09 18:30
It seems to be an issue of the `update` call, which then calls other function. The error itself occures when calling `terms.formula`. However, I'm not sure how to fix this? As renaming the data frame works, I will close this issue for now.

**Closed by sjPlot** 2016-02-09 18:30 UTC
